# backend/cloudbuild.yaml
# Google Cloud Build configuration for Node.js backend

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bala-vihar-backend:latest'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/bala-vihar-backend:latest'
      

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bala-vihar-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bala-vihar-backend:latest'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    env:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://yogeshramakrishnan:pnSCE8RtcPqPetdV@cluster0.qar08.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DB_NAME=sms_db
      - SESSION_SECRET=9e2a7f4d1c8b5e3a9f7d2c6b8e4a1f9d3c7b5e2a8f6d4c1b7e9a3f5d8c2b6e4
      - SESSION_NAME=bala-vihar-session
      - CORS_ORIGIN=https://bala-vihar-frontend-612621646571.us-east1.run.app,http://localhost:5173,http://localhost:3000
      - BCRYPT_ROUNDS=12

images:
    - 'gcr.io/$PROJECT_ID/bala-vihar-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'